name: GCP Cloud Storage Sync
description: >
  > This action deploys static files to a Google Cloud Storage Bucket and sets
  > up the bucket's main and error pages.
author: Antonio Salazar Cardozo, based on work by Abin Mn
branding:
  icon: upload-cloud
  color: blue
inputs:
  service-key:
    description: >
      > GCP service key encoded as base64. The account associated with the key
      > should have permissions to make changes in storage bucket.
    required: true
  project:
    description: Name of the project that contains the storage bucket.
    required: true
  bucket-name:
    description: Bucket name
    required: true
  bucket-path:
    description: >
      > The path in the bucket you want to deploy to. Default is empty. You can
      > change this value if you want to deploy the build-folder contents to
      > something other than the bucket root.
    required: false
    default: .
  build-folder:
    description: >
      > The folder you want to deploy. Default is the repository. You can
      > change this value if you have a build step and point this to that build
      > folder.
    required: false
    default: .
  set-website:
    desription: >
      > Set to "true" if you want website settings like home-page-path and
      > error-page-path applied to the bucket. Leave out otherwise. Note that
      > you must set this to "true" if you want home-page-path and
      > error-page-path to take effect; otherwise, they will be ignored.
    required: false
    default: 'false'
  home-page-path:
    description: >
      > Path of your homepage in cloud storage bucket. Set set-website as well to use this.
    required: false
    default: index.html
  error-page-path:
    description: >
      > Path of the 404 page to be shown. Set set-website as well to use this.
    required: false
    default: 404.html
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.service-key }}
    - ${{ inputs.project }}
    - ${{ inputs.bucket-name }}
    - ${{ inputs.bucket-path }}
    - ${{ inputs.build-folder }}
    - ${{ inputs.set-website }}
    - ${{ inputs.home-page-path }}
    - ${{ inputs.error-page-path }}
