name: Action test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test GCP Deploy
      uses: ./
      with:
        service-key: test-service-key
        project: test-project
        bucket-name: test-bucket-name
      env:
        TEST: 'sk: test-service-key p: test-project bn: test-bucket-name bp: . bf: . hpp: index.html epp: 404.html'
